### PR TITLE
add page about working groups

### PR DESCRIPTION
**Pull request by emiltin**

### CODE REVIEW

**Comment by emiltin** [comment]
I added a new page about the current working groups. Until the branch is complete, th page can be viewed/edited at https://github.com/rsmp-nordic/rsmp-nordic.github.io/blob/c50cadb6a08873655053fe35ac8530798b5b6deb/pages/groups.md

**Comment by emiltin** [comment]
Should working group meeting summaries be posted to the site?

**Comment by otterdahl** [comment]
> Should working group meeting summaries be posted to the site?

I don't think they necessarily need to be. It encourages people to attend meetings.

**Comment by emiltin** [comment]
@otterdahl Hi, did a few updates to this. would you be ok with merging (publishing) this? You can view the new groups page at:
https://github.com/rsmp-nordic/rsmp_website/blob/aea1af8e2accda9af6ebc2ff8d45c3dce93b3ca8/pages/groups.md

I tried to make sure the descriptions are in line with the activity plan. The v4 timeline probably needs to be moved.

**Comment by otterdahl** [comment]
Yes. I think it is OK

**Pull request merged**
